services:
    _defaults:
        autowire: true
    DigipolisGent\Domainator9k\SockBundle\Provider\DataTypeProvider:
        public: true
        tags:
            - { name: data_type_provider }
    DigipolisGent\Domainator9k\SockBundle\Provisioner\BuildSockAccountProvisioner:
        tags:
            - { name: domainator.provisioner.build, priority: 53 }
    DigipolisGent\Domainator9k\SockBundle\Provisioner\BuildSockApplicationProvisioner:
        tags:
            - { name: domainator.provisioner.build, priority: 52 }
    DigipolisGent\Domainator9k\SockBundle\Provisioner\BuildSockDatabaseProvisioner:
        tags:
            - { name: domainator.provisioner.build, priority: 51 }
    DigipolisGent\Domainator9k\SockBundle\Provisioner\PollingProvisioner:
        tags:
            - { name: domainator.provisioner.build, priority: 50 }
    DigipolisGent\Domainator9k\SockBundle\Provisioner\DestroySockDatabaseProvisioner:
        tags:
            - { name: domainator.provisioner.destroy, priority: 12 }
    DigipolisGent\Domainator9k\SockBundle\Provisioner\DestroySockApplicationProvisioner:
        tags:
            - { name: domainator.provisioner.destroy, priority: 11 }
    DigipolisGent\Domainator9k\SockBundle\Provisioner\DestroySockAccountProvisioner:
        tags:
            - { name: domainator.provisioner.destroy, priority: 10 }
    DigipolisGent\Domainator9k\SockBundle\FieldType\ParentApplicationFieldType:
        public: true
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\SockBundle\FieldType\SockAliasesFieldType:
        public: true
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\SockBundle\FieldType\SockServerFieldType:
        public: true
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\SockBundle\FieldType\ManageSockFieldType:
        public: true
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\SockBundle\FieldType\SshKeyChoiceFieldType:
        public: true
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\SockBundle\FieldType\SockApplicationTechnologyFieldType:
        public: true
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\SockBundle\FieldType\DatabaseHostFieldType:
        public: true
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\SockBundle\Service\ApiService:
    DigipolisGent\Domainator9k\SockBundle\EventListener\TaskEventListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist, connection: default }
